### ISSUE TITLE
Reversing task should persist start and finish 

### ISSUE THREAD

**Issue by eehmke** [kflog-project/Cumulus#106]
When I have a task with a start line and a finish cylinder and then do a reverse of the task (change direction) I have a start cylinder and a finish line. This should not happen.

**Comment by speed-axel** [comment]
I think we have to consider two things here.
1. Start and end point of the flight task are different.
2. Start and end point of the flight task are the same.
In the first case the current behavior should not be changed because the points are different.
In the second case I agree to change the current behavior.

**Comment by speed-axel** [comment]
Change executed  as commented before by me.
