### ISSUE TITLE
Only supporting Android <= 6.0

### ISSUE THREAD

**Issue by matc17** [kflog-project/Cumulus#126]
According to Play Store only lower Android versions are allowed. What is the reason?
Imho that's a blocker for future fate of the app.

**Comment by speed-axel** [comment]
Sorry for the long delay of my answer. Google has introduced new requirements to apps with Android 7, which are not realizable with my currently used build tool chain for Qt4. I have to made a migration to Qt5 but that is a bigger act and not to realize in a short time. At August 2018 new Google requirements to apps will be effective, so that Cumulus cannot be load to the Google's play store. For the next winter I plan the migration to Qt5. Because at day I have to work, all migration work have to be done in my free time.

**Comment by speed-axel** [comment]
I made an Android try with Qt5 but there is to much to adapt and therefore I decided, it not to do. Furthermore I cannot push any Cumulus Android packages to GooglePlay. For Android releases < 7 I will provide future packages here on git hub.
